In [ ]:
#Question 1
pip install PyPDF2 py-readability-metrics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.7 MB/s eta 0:00:00


In [ ]:
#Question 2
import nltk

# Download the 'punkt' tokenizer
nltk.download('punkt')

# Download the stopwords
nltk.download('stopwords')

# Download the VADER lexicon
nltk.download('vader_lexicon')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

#Question 3
**Embattled Harvard University President Claudine Gay hit
with more plagiarism charges**

The text discusses President Claudine Gay's experience at Harvard University, where she is being accused of plagiarism. It describes how Harvard was notified of more than forty claims of plagiarism made against Gay, which prompted more investigation into her behavior. The Harvard Corporation, which oversees the university, has backed Gay's leadership in spite of the accusations, even though it has acknowledged that there have been times when her academic publications have not been properly cited. The article focuses on earlier incidents in which Gay is accused of not properly citing her sources in published publications. It also refers to the role played by NAACP President Derrick Johnson in defending Gay against accusations that they were promoting a white nationalist ideology. The article ends by posing the question of whether Harvard, given its past indulgence of faculty accused of academic dishonesty, will hold Gay to the same standards as it does its students in regards to plagiarism accusations. Overall, the article seems to present a critical perspective on the situation, indicating a negative tone.

**Harvard president will submit dissertation edits afterplagiarism allegations**
The essay provides an overview of the latest events surrounding Claudine Gay, the president of Harvard University, and the accusations of plagiarism leveled against her. It describes how, in response to citation problems discovered by a committee, Gay intended to submit revised versions of her 1997 dissertation. She had also already sent in edits to two articles that had already been published. According to the report, concerns have been raised concerning Gay's academic honesty, especially in light of her congressional testimony regarding antisemitism on college campuses. The plagiarism allegations were initially brought to light through a media request by the New York Post. While an initial review found instances of inadequate citation, subsequent investigations revealed duplicative language without proper attribution in Gay's dissertation. Gay will submit three citation corrections for her dissertation. Pressure for Gay's resignation has intensified following her congressional testimony, where she faced criticism for her response to questions about antisemitism. The text also notes the resignation of the president of the University of Pennsylvania in a related context. The tone of the article appears to be neutral, focusing primarily on reporting factual information about the situation involving Harvard University President Claudine Gay and the allegations of plagiarism against her.



In [31]:
#Question 4
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page_num in range(len(reader.pages)):
            text += reader.pages[page_num].extract_text()
    return text

def main():
    pdf_path1 = '/content/foxnews.com-Embattled Harvard University President Claudine Gay hit with more plagiarism charges.pdf'
    pdf_path2 = '/content/reuters.com-Harvard president will submit dissertation edits after plagiarism allegations.pdf'

    # Extract text from PDFs
    text1 = extract_text_from_pdf(pdf_path1)
    text2 = extract_text_from_pdf(pdf_path2)

    return text1, text2

if __name__ == "__main__":
    text1, text2 = main()
    print("Text from Embattled Harvard University President Claudine Gay hit with more plagiarism charges:")
    print(text1)

    print("\nText from Harvard president will submit dissertation edits after plagiarism allegations:")
    print(text2)


Text from Embattled Harvard University President Claudine Gay hit with more plagiarism charges:
1 / 5Brian FloodEmbattled Harvard University President Claudine Gay hit
with more plagiarism charges
foxnews.com /media/embattled-harvard-university-president-claudine-gay-hit-more-plagiarism-charges
Media
Harvard ‘received a complaint outlining over 40 allegations of
plagiarism,’ according to the Free Beacon
 By Brian Flood  Fox News
Published December 20, 2023 12:59pm EST
Harvard president facing 40 new allegations of plagiarism
Fox News' Molly Line reports the latest on the allegations. 
Embattled Harvard University President Claudine Gay  has been slapped with additional
charges of plagiarism. 
The Washington Free Beacon  reported Harvard "received a complaint outlining over 40
allegations of plagiarism" against Gay on T uesday , noting a letter was sent to Harvard's
research integrity of ficer, Stacey Springs, outlining the claims. 
"The document paints a picture of a pattern of miscond

We can see some anomalies in the printed texts.

The first anomaly is missing texts.

The second is garbled characters.

The third is incorrect formatting. As we can see, there are missing line breaks and paragraph spacing, which makes the extracted text difficult to read.

Lastly we have extraction of non-text elements such as "File Photo Acquire Licensing Rights".

In [32]:
#Question 5
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('vader_lexicon')

def analyze_sentiment(text):
    sia = SentimentIntensityAnalyzer()
    sentiment_score = sia.polarity_scores(text)
    return sentiment_score

def main():
    # Analyze sentiment for each article
    sentiment_score1 = analyze_sentiment(text1)
    sentiment_score2 = analyze_sentiment(text2)

    # Compare the results
    print("Sentiment analysis for article 1:", sentiment_score1)
    print("Sentiment analysis for article 2:", sentiment_score2)

if __name__ == "__main__":
    main()


Sentiment analysis for article 1: {'neg': 0.065, 'neu': 0.866, 'pos': 0.07, 'compound': 0.7243}
Sentiment analysis for article 2: {'neg': 0.07, 'neu': 0.904, 'pos': 0.026, 'compound': -0.9719}


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


For article 1:
neg: 0.065 (6.5% of the text is classified as negative sentiment)
neu: 0.866 (86.6% of the text is classified as neutral sentiment)
pos: 0.07 (7% of the text is classified as positive sentiment)
compound: 0.7243 (The overall sentiment of the text is positive, as indicated by the compound score being closer to 1)

For article 2:
neg: 0.07 (7% of the text is classified as negative sentiment)
neu: 0.904 (90.4% of the text is classified as neutral sentiment)
pos: 0.026 (2.6% of the text is classified as positive sentiment)
compound: -0.9719 (The overall sentiment of the text is negative, as indicated by the compound score being closer to -1)

After reading both articles, I found the first article more negative and the second one more neutral. My thoughts contradict with the sentiment analysis.

In [33]:
#Question 6
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

def analyze_sentiment(headline):
    sia = SentimentIntensityAnalyzer()
    sentiment_score = sia.polarity_scores(headline)
    return sentiment_score

def main():
    # Article headlines
    headline1 = "Embattled Harvard University President Claudine Gay hit with more plagiarism charges"
    headline2 = "Harvard president will submit dissertation edits after plagiarism allegations"

    # Analyze sentiment for each headline
    sentiment_score1 = analyze_sentiment(headline1)
    sentiment_score2 = analyze_sentiment(headline2)

    # Print sentiment analysis results
    print("Sentiment analysis for headline 1:", sentiment_score1)
    print("Sentiment analysis for headline 2:", sentiment_score2)

if __name__ == "__main__":
    main()


Sentiment analysis for headline 1: {'neg': 0.192, 'neu': 0.808, 'pos': 0.0, 'compound': -0.3353}
Sentiment analysis for headline 2: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


The results for the article headlines do not agree with the overall sentiment. In our initial sentiment analysis we found that the second article had a more negative sentiment whereas the title for the first article has a more negative sentiment.

In [34]:
#Question 7
from readability import Readability
from readability.exceptions import ReadabilityException

def calculate_readability_scores(text):
    try:
        r = Readability(text)
        fk_score = r.flesch_kincaid()
        gf_score = r.gunning_fog()
        cl_score = r.coleman_liau()
        return fk_score, gf_score, cl_score
    except ReadabilityException as e:
        print("Error:", e)
        return None, None, None

def main():
    # Calculate readability scores for each article
    fk_score1, gf_score1, cl_score1 = calculate_readability_scores(text1)
    fk_score2, gf_score2, cl_score2 = calculate_readability_scores(text2)

    # Print readability scores
    print("Readability scores for article 1:")
    print("Flesch-Kincaid Grade Level:", fk_score1)
    print("Gunning Fog Index:", gf_score1)
    print("Coleman-Liau Index:", cl_score1)
    print("\nReadability scores for article 2:")
    print("Flesch-Kincaid Grade Level:", fk_score2)
    print("Gunning Fog Index:", gf_score2)
    print("Coleman-Liau Index:", cl_score2)

if __name__ == "__main__":
    main()


Readability scores for article 1:
Flesch-Kincaid Grade Level: score: 19.21912993097889, grade_level: '19'
Gunning Fog Index: score: 21.868487077434633, grade_level: 'college_graduate'
Coleman-Liau Index: score: 13.410706836616448, grade_level: '13'

Readability scores for article 2:
Flesch-Kincaid Grade Level: score: 18.706800340389325, grade_level: '19'
Gunning Fog Index: score: 19.59404318689501, grade_level: 'college_graduate'
Coleman-Liau Index: score: 15.241952983725135, grade_level: '15'


**Flesch-Kincaid Grade Level (FKGL):** This metric estimates the U.S. grade level needed to understand the text. A lower score indicates easier readability.

Article 1: Score of approximately 19.22, corresponding to a grade level of '19'.

Article 2: Score of approximately 18.71, corresponding to a grade level of '19'.

The Flesch-Kincaid Grade Level estimates the U.S. grade level required to understand the text. A grade level of '19' indicates that the text is written at a very high level and may be best understood by individuals with extensive educational backgrounds or specialized knowledge.


**Gunning Fog Index (GFI):** This metric estimates the years of formal education required to understand the text. A lower score indicates easier readability.

Article 1: Score of approximately 21.87, corresponding to a grade level of 'college_graduate'.

Article 2: Score of approximately 19.59, also corresponding to a grade level of 'college_graduate'.

The Gunning Fog Index estimates the number of years of formal education required to understand the text. A grade level of 'college_graduate' suggests that the text is written at a level typically understood by individuals with a college-level education or higher.

**Coleman-Liau Index (CLI):** This metric estimates the U.S. grade level needed to understand the text based on characters per word and words per sentence. A lower score indicates easier readability.

Article 1: Score of approximately 13.41, corresponding to a grade level of '13'.

Article 2: Score of approximately 15.24, corresponding to a grade level of '15'.

The Coleman-Liau Index estimates the U.S. grade level required to understand the text based on characters per word and words per sentence. A grade level of '13' or '15' indicates that the text is written at a level generally understood by individuals in the 13th or 15th grade, respectively.


In [35]:
pip install wordcloud

In [36]:
#Question 8
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_word_cloud(text, title):
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(title)
    plt.axis('off')
    plt.show()

def main():
    # Generate word clouds
    generate_word_cloud(text1, "Word Cloud for Article 1")
    generate_word_cloud(text2, "Word Cloud for Article 2")

if __name__ == "__main__":
    main()


For the first word cloud, some words that stood out to me were plagiarism, allegations, complaint, and integrity.

For the second word cloud, dissertation, new, submit and corrections were some words that stood out.

The word cloud for the first text has a more negative selection of words.